use Mix.Config

# this is dev.exs without NGINX. erlang vm on port 443.  
# see old code at top of endpoint.ex for using this plug
# this canonical_host plug is not needed when using NGINX in front of erlang VM.
# eventually need to seperate dev.lov.is from production
# https://github.com/remiprev/plug_canonical_host
# https://sublimecoding.com/how-to-canonicalize-a-domain-in-elixir-phoenix-framework/
# https://sublimecoding.com/301-redirects-in-phoenix/
config :lov,
  canonical_host: "lov.is"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :lov, LovWeb.Endpoint,
  http: [:inet6, port: 80],
  url: [host: "lov.is", port: 443],
  https: [
        :inet6,
        port: 443,
        cipher_suite: :strong,
        keyfile: "/home/lov/certs/lov_is_20190609.key",
        certfile: "/home/lov/certs/lov_is_20190609.crt",
        cacertfile: "/home/lov/certs/lov_is_20190609.ca-bundle",
        dhfile: "/home/lov/certs/dhparams.pem"
      ],
  force_ssl: [hsts: true],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :lov, LovWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/lov_web/{live,views,controllers}/.*(ex)$",
      ~r"lib/lov_web/templates/.*(eex)$",
      ~r"lib/lov/.*(ex)$",
      ~r"lib/lov/{documents}/.*(ex)$",
      ~r"lib/kite/.*(ex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Configure your database
config :lov, Lov.Repo,
  username: "postgres",
  password: "postgres",
  database: "lov_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :lov,
  upload_directory: "/home/lov/upload"

import_config "dev.secret.exs"